---
title: "Reinforcement lab"
author: "Xander Atalay"
date: "11/3/2021"
output:
  html_document:
    toc: yes
    theme: cosmo
    toc_float: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
# Ensuring that the HTML is clean and does not contian code chunks or warnings.
```

```{r Packages}
library(tidyverse)
library(ggplot2)
library(caret)
library(class)
library(RColorBrewer)
library(ROCR)
library(MLmetrics)
library(reticulate)
```

```{r Loading Data}
Mystery <- read.csv("data-frame.csv")
# Let's see what this table looks like:
head(Mystery)
```

```{r Parameter Exploration}
hist(Mystery$num_turns, breaks = 20)
# We can see that the number of turns per game seems to have a max of around 20
cat("Num_turns 5 number summary:")
summary(Mystery$num_turns)

hist(Mystery$cora, breaks = 20)
cat("cora 5 number summary:")
summary(Mystery$cora)

hist(Mystery$corc, breaks = 20)
cat("corc 5 number summary:")
summary(Mystery$corc)
```

```{r Data Relationship Exploration}
ggplot(data = Mystery, aes(x = cora, y = corc, color = main_colors)) + geom_point()
# There seems to be some clustering going on, specifically between main colors.
ggplot(Mystery, aes(x = main_colors, fill = won)) + geom_bar(position="stack")
# This looks like an interesting angle to take, it looks like there are a bunch of different colors, so let's see which ones have the highest winning ratio.
```
```{r Calculating Win Ratios}

color <- unique(Mystery$main_colors)
# List of all of the different colors

winratio <- c()

for (var in color){
  wins <- sum(Mystery[Mystery$main_colors == var,]$won)
  losses <- sum(!Mystery[Mystery$main_colors == var,]$won)
  winrate <- wins / (wins + losses)
  winratio <- append(winratio, winrate)
  # Calculates win ratios for each color
}

Winrates <- data.frame(color, winrate)

ggplot(Winrates, aes(x = color, y =  winratio, fill = winratio)) + geom_col() + ggtitle("Win Ratio vs Color")
# It looks like the best color to play with is BR!
```

```{r Clustering}

Mystery_CVars <- Mystery[,c("cora","corc")]

set.seed(1)
kmeans_Mystery = kmeans(Mystery_CVars, 
                    centers = 6, 
                    algorithm = "Lloyd") 

Mystery_Clusters = as.factor(kmeans_Mystery$cluster)
```

```{r Visualizing Cluster Data}
# What does the kmeans_obj look like?
(ggplot(Mystery, aes(y = cora, 
                x = corc,
                shape = Mystery_Clusters,
                color = main_colors)) + 
  geom_point(size = 6) +
  theme_light())

```
