---
title: "lab5"
author: "Po Wei Tsao"
date: "9/29/2021"
output:
  html_document:
    toc: TRUE
    theme: journal
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(psych)
library(mltools)
library(data.table)
library(caret)
```
[caret documentation](http://topepo.github.io/caret/index.html)

#Dataset 1
## Phase I

```{r}
#Working to developed a model than can predict which colleges will give the highest average grant aid. 

#Assuming we are able to optimizing and make recommendations how does this translate into a business context? 

# Inference versus Prediction 

# Independent Business Metric - Assuming that a high average grant aid will translate into higher grants given to an individual student, can we predict schools are best for those who are dependent on grant aid?

```

## Phase II 

### Scale/Center/Normalizing

```{r}
colleges <- read_csv("data/ForbesAmericasTopColleges2019.csv")
# View(colleges)
colleges = colleges[complete.cases(colleges),]


colleges["avg_aid"] = colleges["Average Grant Aid"]
drops <- c("Rank", "Name", "City", "State", "Website", "Average Grant Aid")
colleges = colleges[ , !(names(colleges) %in% drops)]
# View(colleges)
normalize <- function(x){
 (x - min(x)) / (max(x) - min(x))
}

abc <- names(select_if(colleges, is.numeric))# select function to find the numeric variables 
abc
#Use lapply to normalize the numeric values 

colleges[abc] <- as_tibble(lapply(colleges[abc], normalize))


# View(colleges)

#Looks like columns 2,3,12 and 13 need to be converted to factors
colleges[,c(1)] <- lapply(colleges[,c(1)], as.factor)

View(colleges)


```


### One-hot Encoding 
[ML Tools One-Hot Overview](https://www.rdocumentation.org/packages/mltools/versions/0.3.5/topics/one_hot)

```{r}
# Next let's one-hot encode those factor variables/character 

colleges_1h <- one_hot(as.data.table(colleges),cols = "auto",sparsifyNAs = TRUE,naCols = TRUE,dropCols = TRUE,dropUnusedLevels = TRUE) 
View(colleges_1h)
```


### Baseline/Prevalance 

```{r}
#Essential the target to which we are trying to better with our model. 
describe(colleges_1h$avg_aid)
(box <- boxplot(colleges_1h$avg_aid, horizontal = TRUE)) 
box$stats
fivenum(colleges$avg_aid)

# ?fivenum#thanks Tukey!

#added this a predictor versus replacing the numeric version
(colleges_1h$avg_aid_f <- cut(colleges_1h$avg_aid,c(0, 0.48, 1),labels = c(0,1)))
colleges_1h = colleges_1h[complete.cases(colleges_1h),]

#So no let's check the prevalence 
(prevalence <- table(colleges_1h$avg_aid_f)[[2]]/length(colleges_1h$avg_aid_f))

prevalence
# View(colleges_1h)
```


### Initial Model Building: Decision Tree Style  

```{r}
# Training, Evaluation, Tune, Evaluation, Test, Evaluation
# Divide up our data into three parts, Training, Tuning, and Test

#There is not a easy way to create 3 partitions using the createDataPartitions

#so we are going to use it twice. Mostly because we want to stratify on the variable we are working to predict. What does that mean?  

#clean up our dataset a bit by dropping the original ranking variable and the cereal name which we can't really use. 

colleges_dt <- colleges_1h[,-c("avg_aid")]
# view(colleges_dt)


colleges_part_index_1 <- caret::createDataPartition(colleges_dt$avg_aid_f,
                                           times=1,
                                           p = 0.70,
                                           groups=1,
                                           list=FALSE)
# View(colleges_part_index_1)
dim(colleges_dt)

colleges_train <- colleges_dt[colleges_part_index_1,]
colleges_tune_and_test <- colleges_dt[-colleges_part_index_1, ]

#The we need to use the function again to create the tuning set 

colleges_tune_and_test_index <- createDataPartition(colleges_tune_and_test$avg_aid_f,
                                           p = .5,
                                           list = FALSE,
                                           times = 1)

colleges_tune <- colleges_tune_and_test[colleges_tune_and_test_index, ]
colleges_test <- colleges_tune_and_test[-colleges_tune_and_test_index, ]


dim(colleges_train)
dim(colleges_tune)
dim(colleges_test)


```


#### Using Caret package to fit a C5.0 version of a decision tree
Setting up the cross validation
[Caret_Documentation](http://topepo.github.io/caret/train-models-by-tag.html#Tree_Based_Model)
```{r}
#Cross validation process 

fitControl <- trainControl(method = "repeatedcv",
                          number = 10,
                          repeats = 5, 
                          returnResamp="all") 

# number - number of folds
# repeats - number of times the CV is repeated, here it's 5 take the average of
# those 5 repeats


# Choose the features and classes

```

#### Training and Evaluation 


```{r}
features <- colleges_train[,-"avg_aid_f"]
# view(features)

target <- colleges_train[,"avg_aid_f"]

str(target)

set.seed(1984)
colleges_mdl <- train(x=features,
                y=target$avg_aid_f,
                trControl=fitControl,
                method="C5.0",
                verbose=TRUE)

colleges_mdl

```

Tune and Evaluation 
```{r}
colleges_predict = predict(colleges_mdl, colleges_tune,type= "raw")

confusionMatrix(as.factor(colleges_predict), 
                as.factor(colleges_tune$avg_aid_f), 
                dnn=c("Prediction", "Actual"), 
                mode = "sens_spec")

varImp(colleges_mdl)

plot(colleges_mdl)


grid <- expand.grid(.winnow = c(TRUE,FALSE), 
                    .trials=c(20,30,40), 
                    .model=c("tree","rules"))
set.seed(1984)
colleges_mdl_tune <- train(x=features,
                y=target$avg_aid_f,
                tuneGrid=grid,
                trControl=fitControl,
                method="C5.0",
                verbose=TRUE)

colleges_mdl_tune
colleges_mdl

plot(colleges_mdl_tune)

# Want to evaluation again with the tune data using the new model 

colleges_predict_tune = predict(colleges_mdl_tune,colleges_tune,type= "raw")

confusionMatrix(as.factor(colleges_predict_tune), 
                as.factor(colleges_tune$avg_aid_f), 
                dnn=c("Prediction", "Actual"), 
                mode = "sens_spec")


```

Test 

```{r}
colleges_predict_test = predict(colleges_mdl_tune,colleges_test,type= "raw")
avg_aid = colleges_tune$avg_aid_f[2:length(colleges_tune$avg_aid_f)]

confusionMatrix(as.factor(colleges_predict_test), 
                as.factor(avg_aid), 
                dnn=c("Prediction", "Actual"), 
                mode = "sens_spec")

```


